config/routes.rb
Rails.application.routes.draw do
  root "calculations#index"
  resources :calculations, only: [:index, :create, :destroy] 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calculation.rb
class Calculation < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calculations_controller.rb
class CalculationsController < ApplicationController
  def index
    @calculation = Calculation.new
    @calculations = Calculation.all
  end

  def create
    Calculation.create(calc_params)
    redirect_to :root
  end

  def destroy
    calculation = Calculation.find(params[:id])
    calculation.destroy
    redirect_to :root
  end

  private
  def calc_params
    params.require(:calculation).permit(:title, :product1, :product2, :product3, :product4, :unit_price1, :unit_price2, :unit_price3, :unit_price4, :number1, :number2, :number3, :number4, :sub_total1, :sub_total2, :sub_total3, :sub_total4, :total)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/calculations/_calculation.html.haml
.note__content
  .note__content--title
    = calculation.title
  .note__content--memo
  %ol     
    %li
      = calculation.product1
    %li
      = calculation.unit_price1
      円
    %li
      = calculation.number1
      個
    %li
      = calculation.sub_total1  
      円
    
  .note__content--memo
  %ol     
    %li
      = calculation.product2
    %li
      = calculation.unit_price2 
      円
    %li
      = calculation.number2
      個
    %li
      = calculation.sub_total2
      円
  .note__content--memo
  %ol     
    %li
      = calculation.product3
    %li
      = calculation.unit_price3
      円
    %li
      = calculation.number3
      個
    %li
      = calculation.sub_total3
      円
  .note__content--memo
  %ol     
    %li
      = calculation.product4
    %li
      = calculation.unit_price4
      円
    %li
      = calculation.number4
      個
    %li
      = calculation.sub_total4
      円
  .note__content--memo
  %ol
    %li   
      合計
      = calculation.total
      円
    %li
      = link_to '削除', calculation_path(calculation.id), method: :delete
  

app/views/calculations/index.html.haml
.wrapper
  = form_with model: @calculation, id:"form", local: true do |f|
    .Title 
      = f.text_field :title, class:"Title__form" ,placeholder:"タイトルを入力してください"
    .upbar
      %table.Input_main
        %tr.Input_main__colmun
          %th.Input_main__column--name
            商品
          %th.Input_main__column--name
            単価
          %th.Input_main__column--name
            個数
          %th.Input_main__column--name
            小計
          %th.Input_main__column--name
            合計
        %tr.Input_main__colmun
          %td
            = f.text_field :product1, class:"Input_main__column--name"
          %td
            = f.text_field :unit_price1, class:"Input_main__column--num"
          %td
            = f.text_field :number1, class:"Input_main__column--number"
          %td
            = f.text_field :sub_total1, class:"Input_main__column--sub"
        %tr.Input_main__colmun
          %td
            = f.text_field :product2, class:"Input_main__column--name"
          %td
            = f.text_field :unit_price2, class:"Input_main__column--num"
          %td
            = f.text_field :number2, class:"Input_main__column--number"
          %td
            = f.text_field :sub_total2, class:"Input_main__column--sub"
        %tr.Input_main__colmun
          %td
            = f.text_field :product3, class:"Input_main__column--name"
          %td
            = f.text_field :unit_price3, class:"Input_main__column--num"
          %td
            = f.text_field :number3, class:"Input_main__column--number"
          %td
            = f.text_field :sub_total3, class:"Input_main__column--sub"
        %tr.Input_main__colmun
          %td
            = f.text_field :product4, class:"Input_main__column--name"
          %td
            = f.text_field :unit_price4, class:"Input_main__column--num"
          %td
            = f.text_field :number4, class:"Input_main__column--number"
          %td
            = f.text_field :sub_total4, class:"Input_main__column--sub"
          %td
            = f.text_field :total, class:"Input_main__column--total"
    .Form
      = f.submit "保存する", class:"Form__botton"   

    .note
      = render @calculations

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title AutoCalculation
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
    
  %body
    = yield